import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import localFont from "next/font/local"
import Provider from "./auth/Provider";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500"],
});
const rejouice = localFont({
  src:"../public/fonts/Rejouice-Headline.ttf",
  variable:'--fontname-rejouice'
})
export const metadata = {
  title: "First Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rejouice.className}>
        <Provider>
          <NavBar />
          <main>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
